17 add unit tests
cta-observatory/PulsarTimingAnalysis pull request #25
Opened 2024-10-10 11:27 UTC by cpozogonzalez

1- Add unit test. Using tutorial data.
2- Implement CI to run the test in commit stage.
3- Config ruff to autorun in pre-commit stage.
4- Apply all of the ruff linter changes.

2024-11-12 15:25 UTC, morcuended requested changes

2024-11-12 15:25 UTC, morcuended commented on ptiming_ana/phaseogram/pulsar_analysis.py
> +            P3_limits = None
For another PR, we should improve this `None, "None"` comparison. Right now it keeps the code as it was after the ruff formating.

2024-11-12 15:25 UTC, morcuended commented on ptiming_ana/phaseogram/pulsar_analysis.py
> +            except AttributeError:
I see you always set AttributeError class, it might be that not all error are of that type, but that can be checked later.

2024-11-12 15:25 UTC, morcuended commented on tests/test_tutorial.py
> +import unittest
I've always been using pytest for tests instead of unittest. In the end, they do the same, but I kind of find pytest easier to use, plus shipping fixtures, parameterize features. We can keep this implementation for the time being and see if change to pytest is really needed.

2024-11-12 15:27 UTC, morcuended commented
Thanks @cpozogonzalez for the implementation and changes. They look good overall. Just have a concern about the usage of unittest instead of pytest and some small comments and checks for you to perform.

2024-11-14 14:54 UTC, cpozogonzalez reviewed
All the changes proposed by @morcuended have been fixed. I will be create a new issue to review the exceptions and decide which is the error to catch.

2024-11-14 14:54 UTC, cpozogonzalez commented on ptiming_ana/phaseogram/periodicity_test.py
> -from pylab import *
This script only uses the sum function of pylab. On line 5 is the import. And in a new commit I add the max function importation from decimal.

2024-11-14 14:54 UTC, cpozogonzalez commented on tests/test_tutorial.py
> +import unittest
You are right!! Pytest is easier but I've never use pytest. I will be created a new Issues to change the test framework in the future.

2024-11-14 14:54 UTC, cpozogonzalez commented on tutorial/Tutorial_notebook.ipynb
> -    "from ptiming_ana.phaseogram import *\n",
In the tutorial notebook, form ptiming_ana.phaseogram we only use the PulsarAnalysis class. On line 10 is the importation.

2024-11-14 14:54 UTC, cpozogonzalez commented on ptiming_ana/_version.py
> +
The _version.py was in the .gitignore file. I don't know why the file was upload to github.

2024-11-14 14:58 UTC, cpozogonzalez commented on ptiming_ana/phaseogram/ptime_analysis.py
> -from pylab import *
This script only use the sum function of pylab

2024-11-14 15:01 UTC, cpozogonzalez commented on ptiming_ana/phaseogram/ptime_analysis.py
>              pass
I will be created a new Issue to fix and review the exceptions, we can fix this there.

2024-11-14 15:10 UTC, morcuended approved these changes
Thanks for the clarifications @cpozogonzalez. Looks good to me.

2024-11-14 15:10 UTC, merged

2024-11-14 15:12 UTC, cpozogonzalez commented on ptiming_ana/phaseogram/pulsar_analysis.py
> +            except AttributeError:
We can fix this in #26 Issue